version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    hostname: database_host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    expose:
      - "5432"
    volumes:
      - /var/docker-db-lab:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database_host:5432/shopdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - app_network
    restart: always

volumes:
  db_data:

networks:
  app_network:
